const messages = [
  {
    id: 1,
    createdOn: '2019-03-09T06:57:47.860Z',
    subject: 'Election News',
    message: 'PMB has been re-elected, APC partying hard',
    senderId: 1,
    receiverId: 3,
    parentMessageId: 1,
    status: 'sent',
  },
  {
    id: 2,
    createdOn: '2019-03-03T11:57:47.860Z',
    subject: 'Liverpool wins the EPL',
    message: 'The wait is over, Liverpool FC is EPL champion',
    senderId: 2,
    receiverId: 3,
    parentMessageId: 2,
    status: 'draft',
  },
  {
    id: 3,
    createdOn: '2019-03-06T06:57:47.860Z',
    subject: 'Liverpool wins the EPL',
    message: 'The wait is over, Liverpool FC is EPL champion',
    senderId: 1,
    receiverId: 3,
    parentMessageId: 2,
    status: 'read',
  },
  {
    id: 4,
    createdOn: '2019-02-03T09:57:47.860Z',
    subject: 'Camp Project',
    message: 'Cycle 42 project is tad easy',
    senderId: 2,
    receiverId: 3,
    parentMessageId: 4,
    status: 'unread',
  },
  {
    id: 5,
    createdOn: '2019-03-03T06:57:47.860Z',
    subject: 'Liverpool wins the EPL',
    message: 'The wait is over, Liverpool FC is EPL champion',
    senderId: 3,
    receiverId: 3,
    parentMessageId: 2,
    status: 'read',
  },
  {
    id: 6,
    createdOn: '2019-03-03T08:55:47.860Z',
    subject: 'Camp Project',
    message: 'Cycle 42 project is tad easy',
    senderId: 1,
    receiverId: 3,
    parentMessageId: 4,
    status: 'unread',
  },
];

export default messages;
