const messages = [
  {
    id: 1,
    createdOn: new Date(),
    subject: 'Election News',
    message: 'PMB has been re-elected, APC partying hard',
    parentMessageId: 1,
    status: 'sent',
  },
  {
    id: 2,
    createdOn: new Date(),
    subject: 'Liverpool wins the EPL',
    message: 'The wait is over, Liverpool FC is EPL champion',
    parentMessageId: 2,
    status: 'draft',
  },
  {
    id: 3,
    createdOn: new Date(),
    subject: 'Liverpool wins the EPL',
    message: 'The wait is over, Liverpool FC is EPL champion',
    senderId: 1,
    receiverId: 3,
    parentMessageId: 2,
    status: 'read',
  },
  {
    id: 4,
    createdOn: new Date(),
    subject: 'Camp Project',
    message: 'Cycle 42 project is tad easy',
    senderId: 2,
    receiverId: 3,
    parentMessageId: 4,
    status: 'unread',
  },
  {
    id: 5,
    createdOn: new Date(),
    subject: 'Liverpool wins the EPL',
    message: 'The wait is over, Liverpool FC is EPL champion',
    senderId: 3,
    receiverId: 3,
    parentMessageId: 2,
    status: 'read',
  },
  {
    id: 6,
    createdOn: new Date(),
    subject: 'Camp Project',
    message: 'Cycle 42 project is tad easy',
    senderId: 1,
    receiverId: 3,
    parentMessageId: 4,
    status: 'unread',
  },
];

export default messages;
